import { ClientError } from '../../errors';
import type { ComposeResult } from '../types';
import type { ComposeRequest, ComposerProvider } from './types';

const DEFAULT_MODEL = process.env.SANDBOXES_OPENAI_MODEL ?? 'gpt-5-mini';

interface OpenAIResponse {
  output_text?: string;
  output?: Array<{
    content?: Array<{
      type?: string;
      text?: string;
    }>;
  }>;
}

function extractOutputText(payload: OpenAIResponse): string {
  if (typeof payload.output_text === 'string' && payload.output_text.trim()) return payload.output_text;

  const chunks: string[] = [];
  for (const block of payload.output ?? []) {
    for (const item of block.content ?? []) {
      if (item.type === 'output_text' && typeof item.text === 'string') chunks.push(item.text);
    }
  }
  return chunks.join('\n').trim();
}

function parseCommands(text: string): string[] {
  const lines = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  const commands = lines
    .filter((line) => line.startsWith('`') || /^\d+\./.test(line) || line.startsWith('- '))
    .map((line) =>
      line
        .replace(/^\d+\.\s*/, '')
        .replace(/^-\s*/, '')
        .replace(/^`|`$/g, '')
        .trim(),
    )
    .filter((line) => /^[a-zA-Z0-9].+/.test(line))
    .slice(0, 8);

  return commands;
}

export class OpenAIComposerProvider implements ComposerProvider {
  id = 'openai' as const;

  async compose(input: ComposeRequest): Promise<ComposeResult> {
    const model = input.model?.trim() || DEFAULT_MODEL;
    const systemPrompt =
      'You are a planning assistant for a browser terminal sandbox connected to a GitHub repository. Return concise output with: summary, commands, notes.';

    const response = await fetch('https://api.openai.com/v1/responses', {
      signal: AbortSignal.timeout(60_000),
      method: 'POST',
      headers: {
        Authorization: `Bearer ${input.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model,
        input: [
          { role: 'system', content: [{ type: 'input_text', text: systemPrompt }] },
          {
            role: 'user',
            content: [
              {
                type: 'input_text',
                text: `Repository: ${input.repoFullName} (branch: ${input.branch})\n\nPrompt:\n${input.prompt}\n\nProvide shell-oriented next steps.`,
              },
            ],
          },
        ],
        max_output_tokens: 700,
      }),
    });

    if (!response.ok) {
      const text = await response.text().catch(() => '');
      throw new ClientError(`OpenAI request failed (${response.status}): ${text || 'unknown error'}`, 502);
    }

    const payload = (await response.json()) as OpenAIResponse;
    const text = extractOutputText(payload);
    const summary = text.split(/\r?\n/).find((line) => line.trim()) || 'Generated a workspace plan.';
    const suggestedCommands = parseCommands(text);

    return {
      provider: this.id,
      model,
      summary,
      suggestedCommands,
      notes: ['Generated by remote model via user-provided Codex API key.'],
      usedRemoteModel: true,
    };
  }
}
