import { tagHighlighter, tags } from '@lezer/highlight';

export const appCodeMirrorHighlighter = tagHighlighter([
  { tag: tags.heading, class: 'tok-heading' },
  { tag: tags.heading1, class: 'tok-heading tok-heading1' },
  { tag: tags.heading2, class: 'tok-heading tok-heading2' },
  { tag: tags.heading3, class: 'tok-heading tok-heading3' },
  { tag: tags.strong, class: 'tok-strong' },
  { tag: tags.emphasis, class: 'tok-emphasis' },
  { tag: tags.strikethrough, class: 'tok-strikethrough' },
  { tag: tags.monospace, class: 'tok-monospace' },
  { tag: tags.link, class: 'tok-link' },
  { tag: tags.url, class: 'tok-url' },
  { tag: tags.list, class: 'tok-list' },
  { tag: tags.quote, class: 'tok-quote' },
  { tag: tags.contentSeparator, class: 'tok-contentSeparator' },
  { tag: tags.processingInstruction, class: 'tok-processingInstruction' },
  { tag: tags.meta, class: 'tok-meta' },
  { tag: tags.labelName, class: 'tok-labelName' },
  { tag: tags.string, class: 'tok-string' },
  { tag: tags.regexp, class: 'tok-string tok-regexp' },
  { tag: tags.escape, class: 'tok-escape' },
  { tag: tags.atom, class: 'tok-atom' },
  { tag: tags.bool, class: 'tok-atom tok-bool' },
  { tag: tags.number, class: 'tok-number' },
  { tag: tags.integer, class: 'tok-number' },
  { tag: tags.float, class: 'tok-number' },
  { tag: tags.comment, class: 'tok-comment' },
  { tag: tags.keyword, class: 'tok-keyword' },
  { tag: tags.definitionKeyword, class: 'tok-keyword tok-definitionKeyword' },
  { tag: tags.modifier, class: 'tok-keyword tok-modifier' },
  { tag: tags.operatorKeyword, class: 'tok-keyword tok-operatorKeyword' },
  { tag: tags.variableName, class: 'tok-variableName' },
  { tag: tags.definition(tags.variableName), class: 'tok-variableName tok-definition' },
  { tag: tags.special(tags.variableName), class: 'tok-variableName tok-specialVariable' },
  { tag: tags.propertyName, class: 'tok-propertyName' },
  { tag: tags.attributeName, class: 'tok-attributeName' },
  { tag: tags.typeName, class: 'tok-typeName' },
  { tag: tags.className, class: 'tok-typeName tok-className' },
  { tag: tags.namespace, class: 'tok-typeName tok-namespace' },
  { tag: tags.tagName, class: 'tok-tagName' },
  { tag: tags.attributeValue, class: 'tok-string tok-attributeValue' },
  { tag: tags.operator, class: 'tok-operator' },
  { tag: tags.punctuation, class: 'tok-punctuation' },
  { tag: tags.squareBracket, class: 'tok-punctuation' },
  { tag: tags.paren, class: 'tok-punctuation' },
  { tag: tags.brace, class: 'tok-punctuation' },
  { tag: tags.separator, class: 'tok-punctuation tok-separator' },
  { tag: tags.content, class: 'tok-content' },
  { tag: tags.invalid, class: 'tok-invalid' },
]);
